lib/np_web/router.ex
defmodule NpWeb.Router do
  use NpWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug NpWeb.Auth
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", NpWeb do
    pipe_through :browser # Use the default browser stack

    get "/login",                  SessionController, :new
    post "/login",                 SessionController, :create
    delete "/login/:hash",         SessionController, :delete

    get "/",                       PageController, :index
    get "/page/:number",           PageController, :page

    get "/random",                 AlbumController, :random
    get "/album/index",            AlbumController, :index
    get "/album/new",              AlbumController, :new
    post "/album/new",             AlbumController, :create
    get "/album/:hash",            AlbumController, :show
    get "/album/:hash/delete",     AlbumController, :delete
    get "/album/:hash/:slug",      AlbumController, :show
    get "/album/:hash/:slug/edit", AlbumController, :edit
    put "/album/:hash",            AlbumController, :update
  end

  # Other scopes may use custom stacks.
  # scope "/api", NpWeb do
  #   pipe_through :api
  # end
end

lib/np_web/views/layout_view.ex
defmodule NpWeb.LayoutView do
  use NpWeb, :view
end

lib/np_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Now Playing ∴ Handpicked Albums by the Glitch Family</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>

    <link rel="apple-touch-icon" sizes="180x180" href="<%= Routes.static_path(@conn, "/images/favicons/apple-touch-icon.png") %>">
    <link rel="icon" type="image/png" sizes="32x32" href="<%= Routes.static_path(@conn, "/images/favicons/favicon-32x32.png") %>">
    <link rel="icon" type="image/png" sizes="16x16" href="<%= Routes.static_path(@conn, "/images/favicons/favicon-16x16.png") %>">
    <link rel="manifest" href="<%= Routes.static_path(@conn, "/images/favicons/site.webmanifest") %>">
    <link rel="mask-icon" href="<%= Routes.static_path(@conn, "/images/favicons/safari-pinned-tab.svg") %>" color="#ff2749">
    <meta name="msapplication-TileColor" content="#0e1848">
    <meta name="theme-color" content="#0e1848">

  </head>
  <body>
    <% if @conn.private.phoenix_controller == NpWeb.PageController && @conn.private.phoenix_action == :index do %>
      <header class="header header--home">
    <% else %>
      <header class="header">
    <% end %>
    <header class="header header--home">
      <div class="container">
        <div class="header__left">
          <a class="header__logo glitch--hover" data-text="Now Playing" href="/" title="Homepage">Now Playing</a>
          <div class="header__tagline">Great music should be shared</div>
        </div>
        <nav class="navigation" data-menu="navigation">
          <a class="navigation__item hidden-s-up" href="/">Home</a>
          <%= if @current_user do %>
            <a class="navigation__item navigation__item--admin" href="<%= Routes.album_path(@conn, :new) %>"><span class="hidden-xs-s">+&nbsp;</span>Add</a>
          <% end %>
          <a class="navigation__item active" href="/">Latest</a>
          <%= link "Random", to: Routes.album_path(@conn, :random), class: "navigation__item" %>
          <%= if @current_user do %>
          <div class="navigation__item navigation__item--thin hidden-xs hidden-s">(<%= @current_user.username %>)</div>
          <%= link "Log out", to: Routes.session_path(@conn, :delete, @current_user), method: "delete", class: "navigation__item navigation__item--near" %>
          <% else %>
            <%= link "Login", to: Routes.session_path(@conn, :new), class: "navigation__item" %>
          <% end %>

        </nav>
        <div class="navigation__mobileOverlay" data-menu="overlay"></div>
        <button class="navigation__mobileBtn" data-menu="btn">Menu</button>
      </div>
    </header>

    <main>
      <!-- <div class="container">
        <div class="notif notif--info" role="alert"><%= get_flash(@conn, :info) %></div>
        <div class="notif notif--error" role="alert"><%= get_flash(@conn, :error) %></div>
      </div> -->
      <%= render @view_module, @view_template, assigns %>
    </main>

    <footer class="footer">
      <img class="footer__logo" src="/images/logo-glitch-family.svg" alt="by Glitch Family" title="by Glitch Family">
    </footer>
    <script src="<%= Routes.static_url(@conn, "/js/app.js") %>"></script>
  </body>
</html>